export MACCHINA_BASE=`pwd`
export PROJECT_BASE=$MACCHINA_BASE
export POCO_BASE=$MACCHINA_BASE/platform
export DYLD_LIBRARY_PATH=$POCO_BASE/lib/Darwin/x86_64
export LD_LIBRARY_PATH=$POCO_BASE/lib/Linux/x86_64:$LD_LIBRARY_PATH
